services:
  - type: web
    name: exness-laravel
    runtime: docker        # ✅ Bắt buộc để Render hiểu là dùng Dockerfile
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://exness-laravel.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /tmp/database.sqlite
